version: "3.8"
services:

  app:
    build:
      context: ${PROJECT_DIR}
      dockerfile: images/Dockerfile
    container_name: msc_dissertation
    image: msc_dissertation
    volumes:
      - ${PROJECT_DIR}/:/app
    working_dir: /app
    ports:
      - "8888:8888"
    env_file:
      - .env
