app: msc_dissertation

data_url: https://s3.amazonaws.com/amazon-reviews-pds/tsv/amazon_reviews_us_Gift_Card_v1_00.tsv.gz
data_directory: data/

files:
  header: data/header.tsv
  train_pos: data/train_pos.tsv
  train_neg: data/train_neg.tsv
  test_pos: data/test_pos.tsv
  test_neg: data/test_neg.tsv

filters:
  manual_stopwords_list: ['amazon','card']
  lowercase: True #True or False
  stopwords: True #True or False
  manual_stopwords: True #True or False
  punctuation: True #True or False
  lemmatize: True #True or False

lda:
  num_topics: 2
  coherence: c_v
  min_topics: 2
  max_topics: 11
  step_size: 1
  alpha_min: 0.01
  alpha_max: 1
  alpha_increment: 0.3
  beta_min: 0.01
  beta_max: 1
  beta_increment: 0.3

