app: msc_dissertation

data_url: https://s3.amazonaws.com/amazon-reviews-pds/tsv/amazon_reviews_us_Gift_Card_v1_00.tsv.gz

files:
  header: data/header.tsv
  train_pos: data/train_pos.tsv
  train_neg: data/train_neg.tsv
  test_pos: data/test_pos.tsv
  test_neg: data/test_neg.tsv